version: '3.8'

services:
  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./back_end/.env
    volumes:
      - ./back_end:/app

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front_end:/app
    command: nodemon app.js

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
